//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSVP.Infrastucture.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        public int GuestID { get; set; }
        public int EventID { get; set; }
        public Nullable<int> RsvpID { get; set; }
        public Nullable<int> GuestGroupID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual GuestGroup GuestGroup { get; set; }
        public virtual RSVP RSVP { get; set; }
    }
}
