//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSVP.Infrastucture.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestEventJunction
    {
        public int GuestID { get; set; }
        public int EventID { get; set; }
        public Nullable<int> RepliesID { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Guest Guest { get; set; }
        public virtual Reply Reply { get; set; }
    }
}
